name: Terraform CI

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init (AWS)
        working-directory: aws
        run: terraform init -backend=false

      - name: Terraform Validate (AWS)
        working-directory: aws
        run: terraform validate

    #   GCP validation steps to be enabled after GCP Terraform code is added
      - name: Terraform Init (GCP)
        working-directory: gcp
        run: terraform init -backend=false

      - name: Terraform Validate (GCP)
        working-directory: gcp
        run: terraform validate
